name: Upload all images to R2 CDN

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm start

      - name: Upload to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.S3_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.S3_BUCKET }}
          source-dir: dist/*.png
          destination-dir: ./
